POST http://localhost:3000/api/player/
Content-Type: application/json

{
    "name": "brutha duplicate skills",
    "position": "midfielder",
    "playerSkills": [
        {
            "skill": "defense",
            "value": 200
        },
        {
            "skill": "defense",
            "value": 20
        },
        {
            "skill": "speed",
            "value": 20
        }
    ]
}
###################

PUT http://localhost:3000/api/player/14/
Content-Type: application/json

{
    "name": "Aymen 2",
    "position": "forward",
    "playerSkills": [
        {
            "skill": "strength",
            "value": 608
        }
    ]
}

#########################
DELETE http://localhost:3000/api/player/17/
Authorization: Bearer SkFabTZibXE1aE14ckpQUUxHc2dnQ2RzdlFRTTM2NFE2cGI4d3RQNjZmdEFITmdBQkE= 