POST http://localhost:3000/api/player
Content-Type: application/json

{
    "name": "test",
    "position": "midfielder",
    "playerSkills": [
        {
            "skill": "defense",
            "value": 200
        },
        {
            "skill": "attack",
            "value": 20
        },
        {
            "skill": "speed",
            "value": 20000
        }
    ]
}
###################

PUT http://localhost:3000/api/player/1
Content-Type: application/json

{
    "name": "Aymen 2",
    "position": "forward",
    "playerSkills": [
        {
            "skill": "strength",
            "value": 608
        }
    ]
}

#########################
DELETE http://localhost:3000/api/player/3
Authorization: Bearer SkFabTZibXE1aE14ckpQUUxHc2dnQ2RzdlFRTTM2NFE2cGI4d3RQNjZmdEFITmdBQkE= 

###########################################
POST http://localhost:3000/api/team/process
Content-Type: application/json

[
     {
        "position": "defender",
        "mainSkill": "speed",
        "numberOfPlayers": 1
     },
     {
        "position": "midfielder",
        "mainSkill": "speed",
        "numberOfPlayers": 1
     }
 ]    