POST http://localhost:8000/categories/
Content-Type: application/json

{
  "name": "Clothes"
}
#####
GET http://localhost:8000/categories/

##############

GET http://localhost:8000/categories/4/

############
PUT http://localhost:8000/categories/3/
Content-Type: application/json

{
  "name": "Electronics"
}
#####################
DELETE http://localhost:8000/categories/6/

#####################
POST http://localhost:8000/signup/
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "testpassword"
}
#####################
POST http://localhost:8000/login/
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}
#####################
POST http://localhost:8000/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNTk4MTg3MiwiaWF0IjoxNzI1ODk1NDcyLCJqdGkiOiIwODllZGY0NWM3Yjg0ODNmYmVhYjdhNzY5NzE5ZjlhOCIsInVzZXJfaWQiOjF9.jCDkhmeOzbBqa5VrsyiUnQ1xSFEHqOOz1czkUOU_cik"
}
####################
POST http://localhost:8000/products/
Content-Type: application/json

{
  "name": "T-shirt",
  "description": "A comfortable cotton T-shirt",
  "price": 19.99,
  "qty_stock": 100,
  "category": 1
}
####################
GET http://localhost:8000/products/
####################
GET http://localhost:8000/products/4

####################
PUT http://localhost:8000/products/4/
Content-Type: application/json

{
  "name": "Hoodie",
  "description": "A warm and stylish hoodie",
  "price": 29.99,
  "qty_stock": 50,
  "category": 2
}
####################
DELETE http://localhost:8000/products/1/

####################
GET http://localhost:8000/products/category/1/

####################
POST http://localhost:8000/payments/
Content-Type: application/json

{
  "amount": 100.50,
  "payment_method": "Cash",
  "payment_status": "Completed"
}
####################
GET http://localhost:8000/payments/

####################
GET http://localhost:8000/payments/1/

####################
DELETE  http://localhost:8000/payments/4/
####################
GET http://localhost:8000/check-login/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIwNC1BNC1BRS0zMS1EMi1CMy0yMC02Ri0zRC01Ri1BOC0zQy1BMi0wRC05Ri1BRCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImFkbWluIiwiZXhwIjoxNzI5NTI5NDA0fQ.vZ4WFjlJYTn2t6bYLWznEEqzVq6eQ8P7UVaeQ3r3XsM

####################
POST  http://localhost:8000/updateRequest/
Content-Type: application/json

{
    "id": 0,
    "propertyId": 78,
    "buildingId": null,
    "userId": 1,
    "requestedChanges": "{\"PropertyNumber\":\"updated moez appartment\"}",
    "status": 1
}

####################
####################
####################
####################
####################
####################
####################
####################
####################
####################